
# The release of Jekyll Now
version: v1.2.0


markdown: kramdown
kramdown:
# Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  parse_block_html: true  # 启用HTML块内Markdown解析
